### PR TITLE
Add nginx configuration files and a Docker Compose setup to make running DVWA more reasonable and easier inside servers

### PR DESCRIPTION
**Pull request by prism-zip**
Add nginx configuration files and a Docker Compose setup to make running DVWA more reasonable and easier inside servers, requiring only 'docker-compose up'. This addition comes from my own project witch_craft pwnbox, which uses DVWA  with Alpine Linux. Maybe it doesn't fully align with the project's goals, but it doesn't cost anything.

### CODE REVIEW

**Review by prism-zip — COMMENTED** [review]
All files are reviewed, all good

**Comment by digininja** [comment]
I don't understand the point of this, what is it adding beyond complexity?

The current compose file only requires a `docker compose up`, you haven't changed that part of it.

I don't mind considering this, but I'd need a reason for doing it.

**Comment by digininja** [comment]
Any comment before I close this?

**Comment by digininja** [comment]
Closing as all I can see is this adds unnecessary complexity for no obvious gains.

**Pull request closed without merging**
