### PR TITLE
Added a new installation script which runs in english with more Improvements and better execution command

### PR DESCRIPTION
**Pull request by its-ashu-otf**

### CODE REVIEW

**Comment by digininja** [comment]
What is the difference between your script and @IamCarron's script, it is too much effort to diff the two.

**Comment by its-ashu-otf** [comment]
The  @IamCarron's script doesn't run with english language in kali-linux and I've done some corrections in syntax too. also there is no need to download my script you can just copy paste this one command and get going. :) Also I've worked on more error handling

**Comment by its-ashu-otf** [comment]
Btw Love your Project ❤️

**Comment by digininja** [comment]
It does work in English, you can specify English or Spanish.

**Comment by its-ashu-otf** [comment]
the automatic detection of language doesn't works sir. as u can see
image

**Comment by digininja** [comment]
It used to work, how are you running it? Can you show the command line you
used?

**Comment by its-ashu-otf** [comment]
1. wget https://raw.githubusercontent.com/IamCarron/DVWA-Script/main/Install-DVWA.sh
2. chmod +x Install-DVWA.sh
3. sudo ./Install-DVWA.sh

**Comment by digininja** [comment]
Asking because it looks like it was ran with either sh or a different shell
rather than bash.

I'm interested to know why it stopped working if it has as it did used to
work.

I'll check it and you're version out when I get chance over the next few
days.

**Comment by its-ashu-otf** [comment]
let me check in bash shell too sir

**Comment by IamCarron** [comment]
Hello, @its-ashu-otf ,

I recently ran the installer on the latest version of Kali using the default shell. It worked fine for me. I believe the errors you encountered may depend on the shell you used.

Were you using Terminator?

Could you please provide the output of the locale command?

If you encounter any errors, feel free to open an issue in the project, and I will address it as soon as possible. Thank you for contributing to the project!

Screenshot

**Comment by its-ashu-otf** [comment]
Ahh my bad I just checked my locale and it seems selecting English-India makes locale C.UTF I think thats the reason it was bugging out.  locale
LANG=C.UTF-8
No worries I will close this PR now.

**Comment by IamCarron** [comment]
@its-ashu-otf I will try to add support for more locales so this won't happen again, feel free to open an issue on the project, thanks for letting me know about this problem!

**Comment by its-ashu-otf** [comment]
> @its-ashu-otf I will try to add support for more locales so this won't happen again, feel free to open an issue on the project, thanks for letting me know about this problem!

Sure ❤️

**Comment by digininja** [comment]
I thought there was support for when it didn't get the language.

**Comment by digininja** [comment]
Ashutosh, if you want to submit a PR for an Indian translation that would
be good.

**Comment by its-ashu-otf** [comment]
Sure I will try

**Comment by digininja** [comment]
If you could add a translation for the main README at the same time, that
would be great.

**Comment by IamCarron** [comment]
@digininja Fixed - In the previous version, it wasn't considered that the language could arrive empty. There was an 'else' clause that defaulted the script to English, but it wasn't working correctly. Ideally, if the language variable is not recognized or arrives empty, it should always default to English now.

**Comment by digininja** [comment]
Brilliant, thanks.

**Pull request closed without merging**
