### PR TITLE
Several improvements for broken URL detection test.

### PR DESCRIPTION
**Pull request by songzy12**
1. run once a week
2. try for 5 times, with 3 seconds interval.
3. use the default .ok, rather than explicit status code check.

### CODE REVIEW

**Comment by digininja** [comment]
There is this warning in the build log:

```
  /usr/lib/python3/dist-packages/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings InsecureRequestWarning)
```
I think it is worth turning the checking on as a broken cert may suggest a broken site, even if a page comes back ok, it may not be the page we are expecting.

**Comment by digininja** [comment]
Looks good, let's give it a go.

**Comment by songzy12** [comment]
Took a look at the broken url:

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.dewhurstsecurity.com', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'www.dewhurstsecurity.com' doesn't match 'dewhurstsecurity.com'",),))
```

Maybe I should try to add some message in the output to indicate such cases.

**Comment by digininja** [comment]
Just picked up the first issue. @ethicalhack3r hasn't set his cert up correctly on one of his sites. Getting it all fixed now.

**Comment by digininja** [comment]
Leave it for now, it is a legitimate cert check failure. I've fixed the
about page and told Ryan about it so he can fix his cert.

**Comment by songzy12** [comment]
Sure. Thanks!

**Pull request merged**
