### PR TITLE
Checking for localhost in cookie domain setting

### LINKED ISSUE #546: Browsers rejecting Session Cookie with localhost domain
**Describe the bug**
When DVWA starts a session, code is currently setting HTTP_HOST as the domain in the session cookie. Browsers are rejecting this setting as an incorrect domain name. Should probably add a check to this section of code to unset the domain name if it's localhost
https://www.php.net/manual/en/function.setcookie.php#73107

**To Reproduce**

Steps to reproduce the behaviour:
1. Install current DVWA on local system or in Docker environment
2. Load http://localhost/login.php
3. Observe the browser console error that indicates the cookie violates domain name policy and does not set the cookie

**Expected behaviour**
Session cookie should/must be set to be able to use DVWA. 

**What have you done to help fix the issue yourself?**
Local code rewrite fixes this issue in development environment

**System (please complete the following information):**
 - OS: Ubuntu
 - Database and Version: MariaDB 10.5.18
 - PHP Version 8.1
- Installed PHP modules - mysqli

**Additional context**
https://github.com/digininja/DVWA/blob/1ef8152d87750cee4e4022f9a7556196573575ce/dvwa/includes/dvwaPage.inc.php#L49

Code could probably look something like this
```
$maxlifetime = 86400;
$secure = false;
$domain = ($_SERVER['HTTP_HOST'] == 'localhost') ? false : $_SERVER['HTTP_HOST'];

session_set_cookie_params([
	'lifetime' => $maxlifetime,
	'path' => '/',
	'domain' => $domain,
	'secure' => $secure,
	'httponly' => $httponly,
	'samesite' => $samesite
]);
session_start();
```

### PR DESCRIPTION
**Pull request by sgerlach**
Code change to resolve #546
Check for localhost set domain to false if so, else use the HOST_NAME variable

### CODE REVIEW

**Comment by digininja** [comment]
Looking at the definition for `session_set_cookie_params`, the default for the domain is null, wouldn't that be better than false for localhost?

```php
session_set_cookie_params(
    int $lifetime_or_options,
    ?string $path = null,
    ?string $domain = null,
    ?bool $secure = null,
    ?bool $httponly = null
): bool
```

**Comment by sgerlach** [comment]
I'm unsure about the difference between null and false for this particular function. This example is explicit about false https://www.php.net/manual/en/function.setcookie.php#73107 

In testing, setting the value to null does not unset the domain for the cookie again resulting in

> Cookie “PHPSESSID” has been rejected for invalid domain.

So it appears that it in fact needs to be false to unset the domain name field. (Or make the default false for the definition) but either way still need the logic check somewhere

**Comment by sgerlach** [comment]
Actually, the logic check needs a bit more tweaking looking for a dot in the hostname and then falsing if not contained.  'localhost:8080' does not pass the HTTP_HOST == 'localhost' and the real problem is the lack of a dot in the hostname - Updated code committed

**Comment by sgerlach** [comment]
hmm, more digging is neccesary here - might have to do more with a port number in the hostname if not on a standard port

**Comment by sgerlach** [comment]
Yes, the port number was the actual problem. Even though you technically should not set localhost as the domain, browsers do accept it. Browsers are not happy about port numbers in the domain name for the cookie and are generally not set for same origin policy. This update pulls the hostname part from the HTTP_HOST variable to set the session cookie. Really only comes into play when using non-standard ports to serve DVWA, like in docker scenarios or other non-privileged high port work. Happy to squash these commits if need be. Thanks for the pointer to parse_url @digininja

**Comment by digininja** [comment]
I was about to say that you'd removed the localhost test but if you don't
need it and more then that's great.

I'll give it a quick check later and then accept it.

**Comment by digininja** [comment]
Seems to work, thanks.

**Pull request merged**
