### PR TITLE
Add a GitHub Action to run pytest daily to detect broken urls.

### PR DESCRIPTION
**Pull request by songzy12**
Inspired by https://github.com/digininja/DVWA/pull/374, this PR 
1. added a Github Actions with pytest, where 
2. we extract urls (using regex) from php files (using glob), then
3. use python's requests lib to check their availabilities.

### CODE REVIEW

**Comment by digininja** [comment]
Seems like an ok idea. One thing I spotted from a quick look, it assumes
that all links use single quotes which isn't guaranteed.

I'll have a look at the rest of the code when on a PC later

**Comment by songzy12** [comment]
Thanks for this advice, I just added the regex to also find links with double quotes.

**Comment by digininja** [comment]
I've never set up a GitHub action, how easy are they to do?

Looking at the one you've done, it looks like it has a Cron facility, that
would be good to automate the checks.

**Comment by songzy12** [comment]
To set up the GitHub Action, you just need to create the file `.github/workflows/main.yml` like in this PR.

Then GitHub would setup the configured flow automatically, and then 
1. show a tick or cross sign near your commits: 
cross

2. send you a email when the test fails: 
email

3. you can also check the details at Action tab: 
actions

**Comment by digininja** [comment]
I'm not a Python user, when I try to run this locally it picks up the wrong document root so doesn't test anything. How do I point this at the correct document root?

```
$ python3 -m pytest -s
================================= test session starts ==================================
platform linux -- Python 3.7.3, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /var/sites/dvwa/non-secure/htdocs/tests
collected 1 item                                                                       

test_url.py .

================================== 1 passed in 0.05s ===================================
```

Would the GitHub action pick up the right directory and file?

**Comment by songzy12** [comment]
hi Robin, which directory are you in when you run this command?

When I run this command directly under the top folder (i.e., directly under DVWA/) it can pick the right root dir.
And yes GitHub Actions can pick up the right dir: you can see the third screenshot at https://github.com/digininja/DVWA/pull/376#issuecomment-673590885

**Comment by digininja** [comment]
It wasn't working from the document root, but is now, very odd.

Should it detect every broken link or stop at the first? It has picked up one in about.php but there is at least one more that I deliberately created to see if it would spot it.

**Comment by songzy12** [comment]
Yes currently it will exit after it detects the first broken url.

But I just had an idea about how to detect all broken links at one run. I can submit the code change for this later.

**Comment by digininja** [comment]
I'll pass it back to you then

**Comment by songzy12** [comment]
The idea is to save all the broken urls in a list and check whether its length is 0. 

It should work for multiple broken urls now: 
pytest

**Comment by digininja** [comment]
It doesn't seem to be working, I've created a file in the doc root called test.php with this content:

```
<a href="http://asdfa.notworking/eiwof">test</a>
```

If I then run the script in the same way you do, it only picks up the about.php page with the tmackuk domain.

**Comment by songzy12** [comment]
The reason for the above failure is that we did not check "http" links previously.
I have updated the code again, and now it should work for both "https" and "http" links.

**Comment by digininja** [comment]
It is the smallest things!

It is now picking things up, can you tidy the output a bit? This is what it looks like to me, shouldn't it just give the list of things that failed rather than the full exception and stack trace? If that is hard to do, then leave it, as long as it shows the things that need fixing, it will be obvious and it shouldn't actually trigger that often anyway.

image

**Comment by songzy12** [comment]
hi Robin, 
I did a quick search for this and found this might be the intended behavior of pytest. 
See: https://docs.pytest.org/en/stable/

**Comment by digininja** [comment]
OK, I'll fix up those broken links, check that it is then happy and then
I'll give it a go as an action. Should be easy to test.

**Comment by digininja** [comment]
Finally fixed things up, lets try it out

**Comment by digininja** [comment]
As it merged I got this alert:

https://github.com/digininja/DVWA/actions/runs/234266677

All the links are fixed, do you need to do something so it returns 0 rather than 1?

**Comment by songzy12** [comment]
@digininja hi Robin, you can see the failure message here:
Capture

```
>       assert len(broken_urls) == 0, "Broken URLs Detected."
E       AssertionError: Broken URLs Detected.
E       assert 2 == 0
E        +  where 2 = len([('vulnerabilities/sqli/index.php', 'http://ferruh.mavituna.com/sql-injection-cheatsheet-oku/', 520), ('vulnerabilities/sqli_blind/index.php', 'http://ferruh.mavituna.com/sql-injection-cheatsheet-oku/', 520)])
```

The reason is the request for url `http://ferruh.mavituna.com/sql-injection-cheatsheet-oku/` in file `vulnerabilities/sqli/index.php` returned `520`. 
By a munually check of `http://ferruh.mavituna.com/sql-injection-cheatsheet-oku/`, it seems redirects to `https://www.netsparker.com/blog/web-security/sql-injection-cheat-sheet/`. 
Thus maybe after this modification it should return 0.

**Comment by digininja** [comment]
I hadn't found that bit in the UI but I did run it by hand and that URL didn't show up.

image

I've fixed that and a couple of others that also redirected and the build worked ok so looks like all is good.

Thanks for the work and for sticking with it while I worked out what is going on.

**Comment by songzy12** [comment]
Thanks for taking care of this!

Like what you just mentioned, sometimes the test result seems unstable. 
If this would also happen frequently in the future, we can then introduce some retry mechenism to solve it.

**Comment by digininja** [comment]
Ok let's see how it goes. I can't see things changing much but at least it
will catch things if there do.

**Comment by digininja** [comment]
After working fine for a few days, the script just failed on this

```
tests/test_url.py vulnerabilities/xss_s/index.php	https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet	404
```

If I try to  get that URL I get a 301 redirect to the same URL without the www. I'm hoping that it was just some downtime on the OWASP site but mentioning it just in case.

I'll also update that URL.

**Comment by songzy12** [comment]
Hi Robin,
Do you feel this feature reports false positive too frequently?
I have two ideas:
1. Make it run weekly rather than daily
2. In each run, we test a url for 3 times with 1 second interval. 
    We only think one link is broken if all 3 results are broken. 
    This could help to migitate some temporary failures of certain website.

**Comment by digininja** [comment]
It is getting a way too many false positives.

Running weekly could still get the false positives, we would just see them less. The multiple check might work, but some of the sites I've checked are quite slow to respond which could be causing the problems. Increasing the timeout would help with that.

**Comment by songzy12** [comment]
Sure. Let me do this.

**Comment by digininja** [comment]
Looks like you broke something, I'm getting this in the results:

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lvxoui5r/iniconfig/
Error: Process completed with exit code 1.
```

**Comment by songzy12** [comment]
Acked. I would take a look later.

**Comment by songzy12** [comment]
Just did some search and found [this](https://github.com/pypa/setuptools/issues/2353#issuecomment-684452550),
it seems that the python setuptools is broken.

I have tested with the workaround method in the above link and it worked.
Would send a pull request for this.

**Comment by digininja** [comment]
OK, thanks

**Pull request merged**
