### PR TITLE
feat: allow configuration via environment variables

### PR DESCRIPTION
**Pull request by alles-klar**
Adding the option to configure the dvwa in a docker container via environment variables. This allows users to change the config without rebuiling the docker container.

### CODE REVIEW

**Comment by digininja** [comment]
Looks good, could you write it up into the README so people know it exists and how to use it.

**Comment by alles-klar** [comment]
I was only able to modify the english version.  Hope that helps.

**Comment by digininja** [comment]
That's fine, I'll have a look later.

I've asked all the foreign language translators to keep an eye on the
README so they can keep it updated.

**Comment by digininja** [comment]
Sorry, I missed merging this. Thanks for the contribution.

**Pull request merged**
