### PR TITLE
Add button to test new credentials CSRF

### PR DESCRIPTION
**Pull request by Lijantropique**
When testing the CSRF module, it is required to logout/login to verify the change in credentials. Adding a button beside the form could make this verification easier.

### CODE REVIEW

**Comment by digininja** [comment]
I've not ran the code but it seems like a reasonable idea.

I'm sure you've just taken the login code from the main login page, so the mess around calling mysqli_ functions is ours not yours, but if you could tidy it up it would be a lot better. We need to go through and tidy it up for the rest of the site, but I doubt anyone has time.

**Comment by Lijantropique** [comment]
Yes, basically I copied the login code and remove all the extra references and redirects.  Maybe we can discuss what can be done for the entire site, create some specific tasks, and start working on that in a separate pull request.

**Comment by digininja** [comment]
It's basically tidy up the mess left by the auto upgrade from mysql_ to
mysqli_. It works, but it is messy code.

Should be fairly easy repetitive work once the basics are worked out.

**Comment by Lijantropique** [comment]
Hello, any chance to look at this?

**Comment by digininja** [comment]
It works, but it could be a bit better.

Move the test file into the csrf directory as it is part of that group so may as well be with it.

How about styling up the login success/failure message rather than just leaving it at the bottom looking a bit odd.

Nearly there.

**Comment by Lijantropique** [comment]
I moved the file as requested and added some basic styling. Note that as I was using "dvwaSourceHtmlEcho" for rendering the page, the corresponding CSS rules were added to source.css. Let me know if that is ok. Cheers!

**Comment by digininja** [comment]
That looks good but I've got a small change I'd suggest. There is probably a better way to do this, but I don't know git well enough. Check this branch on my repo:

https://github.com/digininja/DVWA/tree/csrf_button

I've moved the response message into the form and removed the extra padding. There is still a bit too much padding on the top but I couldn't see an easy way to get rid of that.

**Comment by Lijantropique** [comment]
Look at line 41 of test_credentials.php. There is a <br> just after  <fieldset>. If you remove it (or put it after the $login_state), you will remove the padding.

**Comment by digininja** [comment]
If you can integrate that as a change into your PR then that would be good. Would mean you get the credit for it rather than me.

**Comment by Lijantropique** [comment]
<h1>Done</h1>

**Comment by digininja** [comment]
I'll try to remember to get round to checking it, but the code looks like
mine so should work.

**Comment by digininja** [comment]
Sorry this got lost. Thanks for the contribution.

**Pull request merged**
