### PR TITLE
Added support for Anti-CSRF token on high.php (command injection)

### PR DESCRIPTION
**Pull request by stasinopoulos**

### CODE REVIEW

**Comment by stasinopoulos** [comment]
This will make the command injection attack slightly more complex, since the attacker will not be able to use certain automated tools - as testing each generated payload requires a new token.

**Comment by digininja** [comment]
Does that matter? If you want to try out a tool then go for it, if you want
to do it by hand then you can do that as well.

Anyone else got an opinion on it?

**Comment by mike-bailey** [comment]
I think it's tricky. I get the logic behind it but the same could be said for all challenge categories. For instance blind SQL injection I could craft by hand but live I generally do tooling so I don't wanna hate myself. I'd leave the final call to @ethicalhack3r.

**Comment by digininja** [comment]
If this was a CTF type challenge then adding it would be fine as it would
increase the overall complexity but in this instance, I see this doing is
interfering with the point of the module.

**Comment by digininja** [comment]
Keeping each module individual to focus on the specific issue

**Pull request closed without merging**
