### PR TITLE
Fix python setuptools issue in test workflow.

### PR DESCRIPTION
**Pull request by songzy12**
The fix works as in the forked project: https://github.com/songzy12/DVWA

Also renamed the config from "main" to "broken-url-test" to make it more clear.

### CODE REVIEW

**Comment by songzy12** [comment]
Let us wait until the test runs successfully.

**Comment by songzy12** [comment]
It is wired that one run did not catch all the redirected urls.
Also, not too clear why redirected urls would return code 404.

It seems all the urls like "www.owasp.org/index.php" would be eventually changed to something like "owasp.org/www-community/".

**Comment by songzy12** [comment]
Finally, the test is passed.

**Comment by digininja** [comment]
Let's give it a try

**Pull request merged**
